export const Forms: FormList = {
  'vuelos': {
    Code: 'vuelos',
    Title: 'Vuelos',
    Fields: [
      {
        Id: 1,
        Code: 'numero_vuelo',
        Name: 'Vuelo',
        IsRequired: true,
        IsEditable: true,
        Hidden: false,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 2,
        Code: 'hora_salida',
        Name: 'Hora Salida',
        IsRequired: true,
        IsEditable: true,
        Hidden: false,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 3,
        Code: 'hora_llegada',
        Name: 'Hora Llegada',
        IsRequired: true,
        IsEditable: true,
        Hidden: false,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 4,
        Code: 'aeropuerto_origen',
        Name: 'Aeropuerto Origen',
        IsRequired: true,
        IsEditable: true,
        Hidden: false,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 5,
        Code: 'aeropuerto_destino',
        Name: 'Aeropuerto Destino',
        IsRequired: true,
        IsEditable: true,
        Hidden: false,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 6,
        Code: 'id_avion',
        Name: 'Avion',
        IsRequired: true,
        IsEditable: true,
        Hidden: false,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 7,
        Code: 'aeropuerto_destinoNavigation',
        Name: 'Aeropuerto Destino Navigation',
        IsRequired: false,
        IsEditable: false,
        Hidden: true,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 8,
        Code: 'aeropuerto_origenNavigation',
        Name: 'Aeropuerto Origen Navigation',
        IsRequired: false,
        IsEditable: false,
        Hidden: true,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 9,
        Code: 'id_avionNavigation',
        Name: 'Avion Navigation',
        IsRequired: false,
        IsEditable: false,
        Hidden: true,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      },
      {
        Id: 10,
        Code: 'reservas',
        Name: 'Reservas',
        IsRequired: false,
        IsEditable: false,
        Hidden: true,
        MaxLength: 10,
        MinLength: 1,
        Disabled: false,
        Max: 10,
        Min: 1,
        Rules: [],
        DefaultValue: '',
        TypeField: 'text'
      }
    ]
  }
};
